Repository all-contributors/website, pull requests merged in 2019-01, with the labels that each got.

#20 docs(emoji-key): added missing `business` and `content`
  docs/emoji-key.md
  package.json
Labels: documentation, priority: high, status: accepted

#24 doc: doc fix
  docs/emoji-key.md
  docs/repository-maintainers.md
  docs/specification.md
Labels: documentation, priority: low, status: in progress

#28 docs(cli-usage): use inline code to specify the command "generate"
  docs/cli/usage.md
Labels: documentation, good first issue, status: accepted
